//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vahapp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanDetails
    {
        public int LoanDetailID { get; set; }
        public int LoanID { get; set; }
        public int UserID { get; set; }
    
        public virtual Loans Loans { get; set; }
        public virtual Users Users { get; set; }
    }
}
