//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vahapp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loans()
        {
            this.LoanDetails = new HashSet<LoanDetails>();
        }
    
        public int LoanID { get; set; }
        public int UserID { get; set; }
        public int ArticleID { get; set; }
        public System.DateTime Loandate { get; set; }
        public System.DateTime Returndate { get; set; }
        public System.DateTime Duedate { get; set; }
    
        public virtual Articles Articles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanDetails> LoanDetails { get; set; }
        public virtual Users Users { get; set; }
    }
}
