//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vahapp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int NotifID { get; set; }
        public string Sapo { get; set; }
        public byte[] SsHash { get; set; }
        public string Otsikko { get; set; }
        public string Viesti { get; set; }
        public string ExtraField { get; set; }
    }
}
